version: "2"

services:
  cornerwise:
    image: bdsand/cornerwise:latest
    environment:
      APP_MODE: production
      APP_PORT: 3000
    env_file:
      - ./docker-support/common.env
      - ./docker-support/prod.env
    links:
      - postgres
      - redis
    volumes:
      - /datadrive/media:/media
    ports:
      - "3000:3000"
    working_dir: /app
    command: bash /app/start.sh
  postgres:
    image: mdillon/postgis:9.4
    volumes:
      - /datadrive/pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - /datadrive/redis:/data
