version: "2"

services:
  nginx:
    image: nginx
    ports:
      - "3000:80"
    links:
      - cornerwise
    volumes:
      - ./docker-support/cornerwise.conf:/etc/nginx/conf.d/default.conf
      - ./client:/static
      - media:/media:ro
  cornerwise:
    image: bdsand/cornerwise:latest
    env_file:
      - ./docker-support/common.env
    environment:
      APP_MODE: "production"
      DJANGO_SERVE_STATIC: "0"
      DJANGO_SERVE_MEDIA: "0"
    links:
      - postgres
      - redis
    working_dir: /app/
    command: bash /app/start.sh
    volumes:
      - media:/media
      - ./data:/data
      - ./server:/app
  postgres:
    image: mdillon/postgis:9.4
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
  data:
    driver: local
  media:
    driver: local
