version: "2"

services:
  cornerwise:
    image: bdsand/cornerwise:latest
    env_file:
      - ./docker-support/common.env
    links:
      - postgres
      - redis
    working_dir: /app/
    command: bash /app/start.sh
    volumes:
      - media:/media
    working_dir: /app
  postgres:
    image: mdillon/postgis:9.4
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
  data:
    driver: local
  media:
    driver: local
